# Generated by Django 6.0.5 on 2026-05-21 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("slug", models.TextField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": 'arkevent"."event_categories',
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("slug", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("poster_url", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.TextField(default="America/Port-au-Prince")),
                ("venue_name", models.TextField(blank=True, null=True)),
                ("venue_address", models.TextField(blank=True, null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=30)),
                ("visibility", models.CharField(default="public", max_length=30)),
                ("currency", models.TextField(default="HTG")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to="users.profile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": 'arkevent"."events',
            },
        ),
    ]
