# Generated by Django 6.0.5 on 2026-05-23 04:18

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('is_push', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.announcements',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('highlights', models.TextField(blank=True, default='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('poster_url', models.URLField(blank=True, default='')),
                ('banner_url', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('doors_open', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Port-au-Prince', max_length=50)),
                ('venue_name', models.CharField(blank=True, default='', max_length=255)),
                ('venue_address', models.TextField(blank=True, default='')),
                ('venue_city', models.CharField(blank=True, default='', max_length=100)),
                ('venue_state', models.CharField(blank=True, default='', max_length=100)),
                ('venue_country', models.CharField(default='HT', max_length=2)),
                ('venue_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_display', models.CharField(blank=True, default='', max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('online_url', models.URLField(blank=True, default='')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('age_limit', models.CharField(choices=[('all', 'All'), ('parental_guidance', 'Parental Guidance'), ('min_12', '12+'), ('min_16', '16+'), ('min_18', '18+'), ('min_21', '21+')], default='all', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('ticket_opens_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_closes_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='HTG', max_length=3)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('marketing_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('target_audience', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('custom_registration_url', models.URLField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('has_waitlist', models.BooleanField(default=False)),
                ('waitlist_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_transfers', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('checkin_method', models.CharField(choices=[('manual', 'Manual'), ('scan', 'Scan'), ('face', 'Face'), ('code', 'Code')], default='scan', max_length=20)),
                ('event_language', models.CharField(default='fr', max_length=10)),
                ('accessibility_info', models.TextField(blank=True, default='')),
                ('sustainability_info', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arkevent.events',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event categories',
                'db_table': 'arkevent.event_categories',
            },
        ),
        migrations.CreateModel(
            name='EventFaq',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent.event_faq',
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('url', models.URLField()),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.event_media',
            },
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('viewer', 'Viewer'), ('controller', 'Controller')], default='manager', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.event_organizers',
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('session_type', models.CharField(blank=True, choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('performance', 'Performance'), ('panel', 'Panel'), ('break', 'Break'), ('networking', 'Networking'), ('other', 'Other')], max_length=20, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('speakers', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, default='')),
                ('recording_url', models.URLField(blank=True, default='')),
                ('requires_ticket', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arkevent.event_sessions',
            },
        ),
        migrations.CreateModel(
            name='EventShare',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.event_shares',
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.event_speakers',
            },
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('level', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.event_sponsors',
            },
        ),
    ]
