# Generated by Django 6.0.5 on 2026-05-26 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='url',
        ),
        migrations.RemoveField(
            model_name='eventsession',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='eventsession',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='eventspeaker',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='eventsponsor',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='events/posters/'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='events/thumbnails/'),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='events/videos/'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='events/media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sessions/images/'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='sessions/recordings/'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/photos/'),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/logos/'),
        ),
    ]
