# Generated by Django 6.0.5 on 2026-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.CharField(choices=[('general', 'Grand public'), ('students', 'Etudiants'), ('professionals', 'Professionels'), ('families', 'Familles'), ('seniors', 'Personnes âgées'), ('children', 'Enfants'), ('youth', 'Jeunes'), ('developers', 'Développeurs'), ('designers', 'Designers'), ('marketing', 'Marketing'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
