# Generated by Django 6.0.5 on 2026-06-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='speakers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
