# Generated by Django 6.0.5 on 2026-06-15 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_metadata_alter_event_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('general', 'Grand public'), ('students', 'Etudiants'), ('professionals', 'Professionels'), ('families', 'Familles'), ('seniors', 'Personnes âgées'), ('children', 'Enfants'), ('youth', 'Jeunes'), ('developers', 'Développeurs'), ('designers', 'Designers'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=20), blank=True, default=list),
        ),
    ]
