# Generated by Django 6.0.5 on 2026-06-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsponsor',
            name='role',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('viewer', 'Spectateur'), ('controller', 'Contrôleur'), ('organizer', 'Organisateur'), ('presenter', 'Présentateur'), ('speaker', 'Intervenant'), ('other', 'Other')], default='manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('talk', 'Discussion'), ('demo', 'Démonstration'), ('workshop', 'Atelier de travail'), ('performance', 'Performance'), ('panel', 'Panel'), ('break', 'Pause'), ('networking', 'Réseautage'), ('other', 'Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='speakers',
            field=models.ForeignKey(blank=True, db_column='speaker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventspeaker'),
        ),
        migrations.AlterField(
            model_name='eventsponsor',
            name='level',
            field=models.CharField(choices=[('global', 'Global'), ('regional', 'Regional'), ('local', 'Local')], default='', max_length=100),
        ),
    ]
