# Generated by Django 6.0.5 on 2026-06-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventsponsor_role_alter_eventmedia_media_type_and_more'),
        ('events', '0011_fix_target_audience_data'),
    ]

    operations = [
    ]
