# Generated by Django 6.0.5 on 2026-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_id_alter_organizationmember_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/covers/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/logos/'),
        ),
    ]
