# Generated by Django 6.0.5 on 2026-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_organization_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('refused', 'Refused')], default='active', max_length=50),
        ),
    ]
