# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('networking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkingmatch',
            name='user1',
            field=models.ForeignKey(db_column='user1_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkingmatch',
            name='user2',
            field=models.ForeignKey(db_column='user2_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='networkingmatch',
            unique_together={('event', 'user1', 'user2')},
        ),
    ]
