# Generated by Django 6.0.5 on 2026-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social/posts/'),
        ),
    ]
