# Generated by Django 6.0.5 on 2026-05-26 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0003_remove_socialpost_image_url_socialpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkingmatch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
