# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenue_date', models.DateField()),
                ('revenue_month', models.DateField(help_text='First day of month')),
                ('ticket_commission_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('premium_feature_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event_boost_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('ticket_sales_count', models.IntegerField(default=0)),
                ('new_subscriptions_count', models.IntegerField(default=0)),
                ('premium_features_purchased_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent.platform_revenue',
                'ordering': ['-revenue_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_commissions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_ticket_sales', models.IntegerField()),
                ('total_tickets_sold', models.IntegerField()),
                ('average_ticket_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('events_count', models.IntegerField()),
                ('refunds_count', models.IntegerField(default=0)),
                ('refunds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.revenue_reports',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('refunds', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='events.event')),
            ],
            options={
                'db_table': 'arkevent.analytics_daily_metrics',
            },
        ),
        migrations.CreateModel(
            name='EventBoost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boost_type', models.CharField(choices=[('homepage', 'Homepage Featured'), ('trending', 'Trending Section'), ('search_priority', 'Search Priority'), ('recommendation', 'Recommendation Boost')], max_length=30)),
                ('duration', models.CharField(choices=[('7days', '7 Days - 20 USD'), ('30days', '30 Days - 50 USD'), ('90days', '90 Days - 100 USD'), ('180days', '180 Days - 200 USD'), ('365days', '365 Days - 500 USD')], max_length=20)),
                ('cost_htg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='events.event')),
            ],
            options={
                'db_table': 'arkevent.event_boosts',
            },
        ),
    ]
