# Generated by Django 6.0.5 on 2026-05-28 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_alter_announcement_id_alter_eventcategory_id_and_more'),
        ('organization', '0005_remove_organization_cover_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenue_date', models.DateField()),
                ('revenue_month', models.DateField(help_text='First day of month')),
                ('ticket_commission_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('premium_feature_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event_boost_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('ticket_sales_count', models.IntegerField(default=0)),
                ('new_subscriptions_count', models.IntegerField(default=0)),
                ('premium_features_purchased_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent.platform_revenue',
                'ordering': ['-revenue_date'],
                'indexes': [models.Index(fields=['revenue_date'], name='arkevent.pl_revenue_f31a4e_idx'), models.Index(fields=['revenue_month'], name='arkevent.pl_revenue_06c899_idx')],
                'unique_together': {('revenue_date', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='HTG', max_length=3)),
                ('refunds', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='events.event')),
            ],
            options={
                'db_table': 'arkevent.analytics_daily_metrics',
                'indexes': [models.Index(fields=['event', 'metric_date'], name='arkevent.an_event_i_ce6bac_idx')],
                'unique_together': {('event', 'metric_date')},
            },
        ),
        migrations.CreateModel(
            name='EventBoost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boost_type', models.CharField(choices=[('homepage', 'Homepage Featured'), ('trending', 'Trending Section'), ('search_priority', 'Search Priority'), ('recommendation', 'Recommendation Boost')], max_length=30)),
                ('duration', models.CharField(choices=[('7days', '7 Days - 500 HTG'), ('30days', '30 Days - 1000 HTG')], max_length=20)),
                ('cost_htg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='events.event')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'arkevent.event_boosts',
                'indexes': [models.Index(fields=['event', 'is_active'], name='arkevent.ev_event_i_c03293_idx'), models.Index(fields=['expires_at'], name='arkevent.ev_expires_a4deb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_commissions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_ticket_sales', models.IntegerField()),
                ('total_tickets_sold', models.IntegerField()),
                ('average_ticket_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('events_count', models.IntegerField()),
                ('refunds_count', models.IntegerField(default=0)),
                ('refunds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='organization.organization')),
                ('top_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event')),
            ],
            options={
                'db_table': 'arkevent.revenue_reports',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['organizer', 'start_date'], name='arkevent.re_organiz_ef91e5_idx'), models.Index(fields=['period_type', 'start_date'], name='arkevent.re_period__74933b_idx')],
            },
        ),
    ]
