# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('finance', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventboost',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformrevenue',
            index=models.Index(fields=['revenue_date'], name='arkevent.pl_revenue_f31a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrevenue',
            index=models.Index(fields=['revenue_month'], name='arkevent.pl_revenue_06c899_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformrevenue',
            unique_together={('revenue_date', 'currency')},
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='top_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailymetric',
            index=models.Index(fields=['event', 'metric_date'], name='arkevent.an_event_i_ce6bac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsdailymetric',
            unique_together={('event', 'metric_date')},
        ),
        migrations.AddIndex(
            model_name='eventboost',
            index=models.Index(fields=['event', 'is_active'], name='arkevent.ev_event_i_c03293_idx'),
        ),
        migrations.AddIndex(
            model_name='eventboost',
            index=models.Index(fields=['expires_at'], name='arkevent.ev_expires_a4deb8_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuereport',
            index=models.Index(fields=['organizer', 'start_date'], name='arkevent.re_organiz_ef91e5_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuereport',
            index=models.Index(fields=['period_type', 'start_date'], name='arkevent.re_period__74933b_idx'),
        ),
    ]
