# Generated by Django 6.0.5 on 2026-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventboost',
            name='duration',
            field=models.CharField(choices=[('7days', '7 Days - 20 USD'), ('30days', '30 Days - 50 USD'), ('90days', '90 Days - 100 USD'), ('180days', '180 Days - 200 USD'), ('365days', '365 Days - 500 USD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='revenuereport',
            name='currency',
            field=models.CharField(default='HTG', max_length=3),
        ),
    ]
