# Generated by Django 6.0.5 on 2026-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_eventboost_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsdailymetric',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='revenuereport',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
