# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_market_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AddField(
            model_name='marketplacemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_market_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='marketplaceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='marketplaceservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='marketplace.marketplacecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='marketplaceservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marketplace.marketplaceprovider', verbose_name='Prestataire'),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marketplace.marketplaceprovider', verbose_name='Prestataire'),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceavailability',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='marketplace.marketplaceservice', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='events.event', verbose_name='Événement ArkEvent'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='marketplace.marketplaceservice', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='marketplacemessage',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.servicebooking', verbose_name='Réservation'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.servicebooking', verbose_name='Réservation'),
        ),
        migrations.AddField(
            model_name='servicefavorite',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='marketplace.marketplaceservice', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicefavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_services', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.marketplaceservice', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='marketplace.marketplaceservice', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.servicepackage', verbose_name='Pack choisi'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='event_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_reviews', to='events.event', verbose_name='Événement associé'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.marketplaceservice', verbose_name='Service'),
        ),
        migrations.AddIndex(
            model_name='marketplacecategory',
            index=models.Index(fields=['slug', 'is_active'], name='marketplace_slug_adaba8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceprovider',
            index=models.Index(fields=['business_name'], name='marketplace_busines_a45905_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceprovider',
            index=models.Index(fields=['city', 'verified'], name='marketplace_city_31085e_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceservice',
            index=models.Index(fields=['status', 'service_type', 'base_price'], name='marketplace_status_074c35_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceservice',
            index=models.Index(fields=['is_featured'], name='marketplace_is_feat_a5f67e_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceavailability',
            constraint=models.UniqueConstraint(fields=('service', 'date', 'start_time'), name='unique_service_availability'),
        ),
        migrations.AddConstraint(
            model_name='servicefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_user_favorite_service'),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('service', 'reviewer')},
        ),
    ]
