# Generated by Django 6.0.5 on 2026-06-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceservice',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='marketplaceservice',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total avis'),
        ),
        migrations.AlterField(
            model_name='marketplaceprovider',
            name='country',
            field=models.CharField(default='Haïti', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='marketplaceservice',
            name='country',
            field=models.CharField(default='Haïti', max_length=100, verbose_name='Pays'),
        ),
    ]
