# Generated by Django 6.0.5 on 2026-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_affiliate_id_alter_affiliatetransaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
