# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('event_boost', 'Event Boost'), ('custom_branding', 'Custom Branding'), ('sponsored_ads', 'Sponsored Ads'), ('api_addon', 'API Add-on'), ('priority_support', 'Priority Support')], max_length=50, unique=True)),
                ('price_htg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent"."premium_features',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], max_length=20, unique=True)),
                ('price_htg', models.DecimalField(decimal_places=2, default=0, help_text='Price in HTG', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, help_text='Price in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('max_active_events', models.IntegerField(blank=True, help_text='NULL = unlimited', null=True)),
                ('max_tickets_per_event', models.IntegerField(blank=True, help_text='NULL = unlimited', null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('requires_branding', models.BooleanField(default=True, help_text='Must show ArkEvent branding')),
                ('has_qr_checkin', models.BooleanField(default=False)),
                ('has_basic_analytics', models.BooleanField(default=True)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_custom_pages', models.BooleanField(default=False)),
                ('has_marketing_tools', models.BooleanField(default=False)),
                ('has_multi_admin', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_custom_domain', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('has_sponsor_placement', models.BooleanField(default=False)),
                ('priority_support_level', models.CharField(choices=[('none', 'No Support'), ('basic', 'Email Support'), ('priority', 'Priority Support'), ('dedicated', 'Dedicated Support')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent"."subscription_plans',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('purchase_token', models.TextField(blank=True, null=True, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent"."user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserPremiumFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_features', to='events.event')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.premiumfeature')),
            ],
            options={
                'db_table': 'arkevent"."user_premium_features',
            },
        ),
    ]
