# Generated by Django 6.0.5 on 2026-05-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='purchase_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
