# Generated by Django 6.0.5 on 2026-05-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
