# Generated by Django 6.0.5 on 2026-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpremiumfeature',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
