# Generated by Django 6.0.5 on 2026-06-15 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=50)),
                ('validation_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.attendances',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('attendee', 'Attendee'), ('speaker', 'Speaker'), ('staff', 'Staff'), ('vip', 'VIP'), ('press', 'Press'), ('exhibitor', 'Exhibitor')], default='attendee', max_length=20)),
                ('badge_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.badges',
            },
        ),
        migrations.CreateModel(
            name='RegistrationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.registration_answers',
            },
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('file', 'File'), ('number', 'Number')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arkevent.registration_fields',
            },
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default="Formulaire d'inscription", max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent.registration_forms',
            },
        ),
    ]
