# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ticket',
            field=models.OneToOneField(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='tickets.ticket'),
        ),
    ]
