# Generated by Django 6.0.5 on 2026-05-23 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('payments', '0002_initial'),
        ('registrations', '0002_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badge',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='events.event'),
        ),
        migrations.AddField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationanswer',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='registration_answers', to='payments.order'),
        ),
        migrations.AddField(
            model_name='registrationanswer',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='ticket_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='registrationanswer',
            name='field',
            field=models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='registrations.registrationfield'),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='events.event'),
        ),
        migrations.AddField(
            model_name='registrationfield',
            name='form',
            field=models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='registrations.registrationform'),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('event', 'user', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='registrationform',
            unique_together={('event',)},
        ),
    ]
