# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('organization', '0002_initial'),
        ('payments', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_seller', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='events.event'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket_type',
            field=models.ForeignKey(db_column='ticket_type_id', on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='commission_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.commissionrule'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_sales', to='events.event'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.order'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='ticket_sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_request', to='payments.ticketsale'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ticket_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.ticketsale'),
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['event', 'created_at'], name='ticket_sale_event_i_ade934_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['buyer', 'created_at'], name='ticket_sale_buyer_i_3e7fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['payment_status'], name='ticket_sale_payment_f08197_idx'),
        ),
    ]
