# Generated by Django 6.0.5 on 2026-05-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("tickets", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="ticket_type",
            field=models.ForeignKey(
                db_column="ticket_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.tickettype",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                db_column="order_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="users.profile",
            ),
        ),
    ]
