# Generated by Django 6.0.5 on 2026-05-27 13:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_announcement_id_alter_eventcategory_id_and_more'),
        ('organization', '0005_remove_organization_cover_url_and_more'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage Based (%)'), ('fixed', 'Fixed Amount'), ('hybrid', 'Percentage + Fixed')], max_length=20)),
                ('deduction_model', models.CharField(choices=[('organizer', 'Deducted from Organizer Revenue'), ('customer', 'Added to Customer Checkout')], default='organizer', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_currency', models.CharField(default='HTG', help_text='Currency for fixed amount', max_length=3)),
                ('subscription_tier', models.CharField(blank=True, choices=[('free', 'Free Plan'), ('pro', 'Pro Plan'), ('business', 'Business Plan')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arkevent"."commission_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('digicel', 'Digicel Payment'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'arkevent"."payment_methods',
            },
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ticket_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='HTG', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organizer_net_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_purchases', to=settings.AUTH_USER_MODEL)),
                ('commission_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.commissionrule')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_sales', to='events.event')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.order')),
            ],
            options={
                'db_table': 'arkevent"."ticket_sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_reason', models.CharField(choices=[('duplicate', 'Duplicate Charge'), ('not_as_described', 'Not As Described'), ('cant_attend', "Can't Attend"), ('event_cancelled', 'Event Cancelled'), ('other', 'Other')], max_length=50)),
                ('reason_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_reviewed', to=settings.AUTH_USER_MODEL)),
                ('ticket_sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_request', to='payments.ticketsale')),
            ],
            options={
                'db_table': 'arkevent"."refund_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('sale', 'Ticket Sale'), ('refund', 'Refund'), ('subscription', 'Subscription'), ('premium_feature', 'Premium Feature')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='HTG', max_length=3)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_seller', to='organization.organization')),
                ('ticket_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.ticketsale')),
            ],
            options={
                'db_table': 'arkevent"."invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['event', 'created_at'], name='ticket_sale_event_i_ade934_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['buyer', 'created_at'], name='ticket_sale_buyer_i_3e7fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['payment_status'], name='ticket_sale_payment_f08197_idx'),
        ),
    ]
