# Generated by Django 6.0.5 on 2026-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_commissionrule_paymentmethod_ticketsale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrule',
            name='fixed_currency',
            field=models.CharField(default='USD', help_text='Currency for fixed amount', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.TextField(default='USD'),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
