# Generated by Django 6.0.5 on 2026-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_commissionrule_fixed_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.TextField(default='USD'),
        ),
    ]
