# Generated by Django 6.0.5 on 2026-05-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("timezone", models.TextField(default="UTC")),
                ("language", models.TextField(default="fr")),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("cover_url", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("social_links", models.JSONField(default=dict)),
                ("role", models.CharField(default="user", max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("notification_preferences", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("referral_code", models.TextField(blank=True, null=True, unique=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="referred_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "db_table": 'arkevent"."profiles',
            },
        ),
    ]
