# Generated by Django 6.0.5 on 2026-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('controller', 'Controller'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
