# Generated by Django 6.0.5 on 2026-05-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_emailverificationtoken_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='wallet_balance_non_negative',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
