# Generated by Django 6.0.5 on 2026-05-23 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickethold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettransfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettransfer',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='tickettransfer',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event'),
        ),
        migrations.AddField(
            model_name='tickethold',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(db_column='ticket_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['status'], name='arkevent_ti_status_d4ca2f_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['transfer_token'], name='arkevent_ti_transfe_0bcf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['expires_at'], name='arkevent_ti_expires_f06862_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['from_user'], name='arkevent_ti_from_us_8834e2_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['to_user'], name='arkevent_ti_to_user_c24a4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettransfer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'declined', 'cancelled'])), name='ticket_transfers_status_valid'),
        ),
        migrations.AddIndex(
            model_name='tickethold',
            index=models.Index(fields=['expires_at'], name='arkevent_ti_expires_88ff63_idx'),
        ),
        migrations.AddIndex(
            model_name='tickethold',
            index=models.Index(fields=['user'], name='arkevent_ti_user_id_be352b_idx'),
        ),
        migrations.AddIndex(
            model_name='tickethold',
            index=models.Index(fields=['ticket_type'], name='arkevent_ti_ticket__3af81d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickethold',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ticket_holds_quantity_gt_0'),
        ),
    ]
