# Generated by Django 6.0.5 on 2026-05-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category_alter_event_created_by_and_more'),
        ('payments', '0003_alter_order_event_alter_orderitem_order_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(db_column='order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='payments.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(db_column='ticket_type', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(db_column='event', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event'),
        ),
    ]
