# Generated by Django 6.0.5 on 2026-06-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checkin_method',
            field=models.CharField(blank=True, choices=[('scan', 'Scan QR Code'), ('manual', 'Manual Verification')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qrcodes/'),
        ),
    ]
