# Generated by Django 6.0.5 on 2026-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_checkin_method_ticket_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_ticket',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdfs/'),
        ),
    ]
