# Generated by Django 6.0.5 on 2026-05-23 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('marketing', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='organization.organization'),
        ),
    ]
