# Generated by Django 6.0.5 on 2026-05-27 13:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_commissionrule_paymentmethod_ticketsale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('HTG', 'Haitian Gourde'), ('USD', 'US Dollar')], default='HTG', max_length=3)),
                ('is_frozen', models.BooleanField(default=False, help_text='Freeze wallet during disputes or investigations')),
                ('freeze_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'arkevent"."wallets',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='HTG', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payout_period_start', models.DateField()),
                ('payout_period_end', models.DateField()),
                ('destination_provider', models.CharField(max_length=50)),
                ('destination_identifier', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('included_ticket_sales_count', models.IntegerField(default=0)),
                ('included_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='wallets.wallet')),
            ],
            options={
                'db_table': 'arkevent"."payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD')], default='HTG', max_length=3)),
                ('deposit_method', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('digicel', 'Digicel Payment'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallets.wallet')),
            ],
            options={
                'db_table': 'arkevent"."deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('ticket_sale', 'Ticket Sale Commission'), ('refund', 'Refund'), ('payout', 'Payout'), ('subscription_charge', 'Subscription Charge'), ('premium_feature_charge', 'Premium Feature Charge'), ('adjustment', 'Manual Adjustment')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='HTG', max_length=3)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_ticket_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.ticketsale')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'arkevent"."wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD')], default='HTG', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withdrawal_speed', models.CharField(choices=[('standard', 'Standard (Free)'), ('instant', 'Instant (100 HTG fee)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('destination_provider', models.CharField(max_length=50)),
                ('destination_identifier', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallets.wallet')),
            ],
            options={
                'db_table': 'arkevent"."withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['wallet', 'created_at'], name='payouts_wallet__f68693_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payouts_status_20cd29_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['wallet', 'created_at'], name='deposits_wallet__bad096_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['status'], name='deposits_status_46b764_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__aa27da_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_tran_status_c987ce_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_id'], name='wallet_tran_referen_1f3089_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['wallet', 'created_at'], name='withdrawals_wallet__1e649c_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='withdrawals_status_ddef8f_idx'),
        ),
    ]
