# Generated by Django 6.0.5 on 2026-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('HTG', 'Haitian Gourde'), ('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD')], default='USD', max_length=3),
        ),
    ]
