# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventanalyticsdaily',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventview',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventview',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventanalyticsdaily',
            unique_together={('event', 'date')},
        ),
    ]
